version: "3.4"

services:
  dice-city-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: always
    ports:
      - "${PORT}:8080"
    command: node ./dist-back/main.js
  dice-city-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: always
    command: node ./dist-back/worker.js
  redis:
    restart: always
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./volumes/redis:/data
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
